version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    volumes:
      - .:/app 
      - /app/node_modules 
    ports:
      - "5173:3000" 

